services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: global_jenkins
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - global_jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  global_jenkins_data:
